### ISSUE TITLE
why the solution to the maze its always south east direction?, can you add more maze algorithms?

### ISSUE THREAD

**Issue by tungdd2009** [armin-reichert/mazes#2]

**Comment by armin-reichert** [comment]
I don't understand your question, can you please be more specific?

**Comment by tungdd2009** [comment]
[same direction.docx](https://github.com/armin-reichert/mazes/files/7189074/same.direction.docx)
i mean the mazes all go in a pattern look at the file

**Comment by armin-reichert** [comment]
That's the default setting for "Solution Start" and "Solution End" and can be changed using the "Options" menu of the demo program.
